<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'slug' => 'heavy-duty-display-rack',
                'name' => 'Heavy Duty Display Rack',
                'desc' => '5-tier shelving, 900mm width, adjustable shelves.',
                'cat' => 'supermarket',
                'cat_label' => 'Supermarket Rack',
                'badge' => 'Best Seller',
                'image' => 'products.png',
                'price' => 4200,
                'old_price' => 4960,
                'specs' => [
                    'Overall Dimensions' => '900mm (W) x 450mm (D) x 1800mm (H)',
                    'Number of Shelves' => '5, fully adjustable',
                    'Load Capacity' => '80kg per shelf / 400kg total',
                    'Frame Material' => 'High-tensile CRCA steel, 1.2mm thickness',
                    'Shelf Material' => 'CRCA steel, 0.8mm thickness',
                    'Finish' => 'Epoxy powder coating, anti-rust',
                    'Color Options' => 'Red/White, Grey, Custom (on request)',
                    'Warranty' => '2 years structural warranty',
                ],
            ],
            [
                'slug' => 'slotted-angle-rack-ms',
                'name' => 'Slotted Angle Rack MS',
                'desc' => '6-shelf bolt-free rack, 200kg/shelf load capacity.',
                'cat' => 'slotted-angle',
                'cat_label' => 'Slotted Angle Rack',
                'badge' => null,
                'image' => 'products2.png',
                'price' => 2850,
                'old_price' => 3360,
                'specs' => [
                    'Overall Dimensions' => '900mm (W) x 450mm (D) x 2000mm (H)',
                    'Number of Shelves' => '6, bolt-free adjustable',
                    'Load Capacity' => '200kg per shelf / 1200kg total',
                    'Frame Material' => 'Mild steel slotted angle, 2mm thickness',
                    'Shelf Material' => 'MS sheet, 0.6mm thickness',
                    'Finish' => 'Powder coated, anti-rust',
                    'Color Options' => 'Blue, Grey, Custom (on request)',
                    'Warranty' => '1 year structural warranty',
                ],
            ],
            [
                'slug' => 'industrial-pallet-rack',
                'name' => 'Industrial Pallet Rack',
                'desc' => 'Heavy-duty warehouse racking, 2000kg/level capacity.',
                'cat' => 'warehouse',
                'cat_label' => 'Warehouse Rack',
                'badge' => 'New',
                'image' => 'products3.png',
                'price' => 9500,
                'old_price' => 11210,
                'specs' => [
                    'Overall Dimensions' => '2700mm (W) x 1100mm (D) x 6000mm (H)',
                    'Number of Levels' => '3, forklift accessible',
                    'Load Capacity' => '2000kg per level / 6000kg total',
                    'Frame Material' => 'High-tensile steel, 3mm thickness',
                    'Beam Material' => 'Cold rolled steel box beams',
                    'Finish' => 'Epoxy powder coating',
                    'Color Options' => 'Orange/Blue, Custom (on request)',
                    'Warranty' => '3 years structural warranty',
                ],
            ],
            [
                'slug' => 'godown-storage-rack',
                'name' => 'Godown Storage Rack',
                'desc' => '4-tier multi-purpose rack for bulk goods storage.',
                'cat' => 'storage',
                'cat_label' => 'Storage Rack',
                'badge' => null,
                'image' => 'products4.png',
                'price' => 5100,
                'old_price' => 6020,
                'specs' => [
                    'Overall Dimensions' => '1200mm (W) x 600mm (D) x 2100mm (H)',
                    'Number of Shelves' => '4, adjustable',
                    'Load Capacity' => '150kg per shelf / 600kg total',
                    'Frame Material' => 'MS angle, 2mm thickness',
                    'Shelf Material' => 'MS sheet, 0.8mm thickness',
                    'Finish' => 'Powder coated, anti-rust',
                    'Color Options' => 'Grey, Custom (on request)',
                    'Warranty' => '1 year structural warranty',
                ],
            ],
            [
                'slug' => 'compact-display-rack',
                'name' => 'Compact Display Rack',
                'desc' => '4-tier shelving, 600mm width, ideal for small stores.',
                'cat' => 'supermarket',
                'cat_label' => 'Supermarket Rack',
                'badge' => null,
                'image' => 'compact.png',
                'price' => 3400,
                'old_price' => 4010,
                'specs' => [
                    'Overall Dimensions' => '600mm (W) x 400mm (D) x 1500mm (H)',
                    'Number of Shelves' => '4, adjustable',
                    'Load Capacity' => '60kg per shelf / 240kg total',
                    'Frame Material' => 'CRCA steel, 1mm thickness',
                    'Shelf Material' => 'CRCA steel, 0.7mm thickness',
                    'Finish' => 'Epoxy powder coating',
                    'Color Options' => 'Red/White, Custom (on request)',
                    'Warranty' => '2 years structural warranty',
                ],
            ],
            [
                'slug' => 'adjustable-storage-rack',
                'name' => 'Adjustable Storage Rack',
                'desc' => '8-shelf tall unit, ideal for offices & godowns.',
                'cat' => 'slotted-angle',
                'cat_label' => 'Slotted Angle Rack',
                'badge' => null,
                'image' => 'adjustable.png',
                'price' => 3950,
                'old_price' => 4660,
                'specs' => [
                    'Overall Dimensions' => '900mm (W) x 450mm (D) x 2400mm (H)',
                    'Number of Shelves' => '8, bolt-free adjustable',
                    'Load Capacity' => '150kg per shelf / 1200kg total',
                    'Frame Material' => 'MS slotted angle, 2mm thickness',
                    'Shelf Material' => 'MS sheet, 0.6mm thickness',
                    'Finish' => 'Powder coated, anti-rust',
                    'Color Options' => 'Blue, Grey, Custom (on request)',
                    'Warranty' => '1 year structural warranty',
                ],
            ],
            [
                'slug' => 'selective-pallet-rack',
                'name' => 'Selective Pallet Rack',
                'desc' => '3-level heavy racking with forklift access aisles.',
                'cat' => 'warehouse',
                'cat_label' => 'Warehouse Rack',
                'badge' => null,
                'image' => 'selective.png',
                'price' => 11200,
                'old_price' => 13220,
                'specs' => [
                    'Overall Dimensions' => '2700mm (W) x 1100mm (D) x 7500mm (H)',
                    'Number of Levels' => '4, forklift accessible',
                    'Load Capacity' => '2200kg per level / 8800kg total',
                    'Frame Material' => 'High-tensile steel, 3mm thickness',
                    'Beam Material' => 'Cold rolled steel box beams',
                    'Finish' => 'Epoxy powder coating',
                    'Color Options' => 'Orange/Blue, Custom (on request)',
                    'Warranty' => '3 years structural warranty',
                ],
            ],
            [
                'slug' => 'cold-storage-rack',
                'name' => 'Cold Storage Rack',
                'desc' => 'Rust-proof coated rack for cold storage units.',
                'cat' => 'storage',
                'cat_label' => 'Storage Rack',
                'badge' => null,
                'image' => 'Popular3.png',
                'price' => 6700,
                'old_price' => 7910,
                'specs' => [
                    'Overall Dimensions' => '1200mm (W) x 600mm (D) x 2100mm (H)',
                    'Number of Shelves' => '5, adjustable',
                    'Load Capacity' => '120kg per shelf / 600kg total',
                    'Frame Material' => 'Galvanized steel, 2mm thickness',
                    'Shelf Material' => 'Galvanized steel, 0.8mm thickness',
                    'Finish' => 'Hot-dip galvanized, rust-proof',
                    'Color Options' => 'Silver (galvanized finish)',
                    'Warranty' => '3 years structural warranty',
                ],
            ],
            [
                'slug' => 'wall-mounted-display-rack',
                'name' => 'Wall Mounted Display Rack',
                'desc' => 'Space-saving wall unit, 3-tier, powder coated finish.',
                'cat' => 'supermarket',
                'cat_label' => 'Supermarket Rack',
                'badge' => 'Popular',
                'image' => 'wallmounted.png',
                'price' => 2600,
                'old_price' => 3070,
                'specs' => [
                    'Overall Dimensions' => '900mm (W) x 300mm (D) x 1200mm (H)',
                    'Number of Shelves' => '3, adjustable',
                    'Load Capacity' => '40kg per shelf / 120kg total',
                    'Frame Material' => 'CRCA steel, 1mm thickness',
                    'Shelf Material' => 'CRCA steel, 0.6mm thickness',
                    'Finish' => 'Epoxy powder coating',
                    'Color Options' => 'White, Custom (on request)',
                    'Warranty' => '2 years structural warranty',
                ],
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(['slug' => $product['slug']], $product);
        }
    }
}